/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures
/*
 // Enable this only when using 64 bit archictecture
struct _NSPoint {
    float x;
    float y;
};

struct _NSSize {
    float width;
    float height;
};

struct _NSRect {
    struct _NSPoint origin;
    struct _NSSize size;
};
*/

